type: "crud-v1"
entityName: Agendamento
entityNamePlural: Agendamentos
description: Agendamento de visita
name: agendamentos
readMenu: Agendamentos//Visualizar
createMenu: Agendamentos//Cadastrar
fields: 
  - cliente
  - data_da_visita
