type: "crud-v1"
entityName: Agendamento
entityNamePlural: Agendamentos
description: Agendamento de visita
name: agendamentos
readMenu: Visualizar//Agendamentos
createMenu: Cadastrar//Agendamentos
fields: 
  - cliente
  - data_da_visita
