type: "crud-v1"
entityName: Escopo
entityNamePlural: Escopos
description: Escopo
name: escopo
readMenu: Visualizar//Escopos
createMenu: Cadastrar//Escopos
fields: 
  - agendamento
  - descricao_servico
  - mao_obra
  - material
