type: "crud-v1"
entityName: Cliente
entityNamePlural: Clientes
description: Cadastro de Clientes
name: clientes
readMenu: Visualizar//Clientes
createMenu: Cadastrar//Clientes
fields: 
  - nome_fantasia
  - razao_social
  - cnpj
  - insc_estadual
  - insc_municipal
  - telefone
  - cep
  - logradouro
  - numero
  - complemento
  - bairro
  - cidade
  - estado
