type: "crud-v1"
entityName: Cliente
entityNamePlural: Clientes
description: Cadastro de Clientes
name: clientes
readMenu: Clientes//Visualizar
createMenu: Clientes//Cadastrar
fields: 
  - nome_fantasia
  - razao_social
  - cnpj
  - insc__estadual
  - insc__municipal
  - telefone
  - cep
  - logradouro
  - numero
  - complemento
  - bairro
  - cidade
  - estado
