type: "crud-v1"
entityName: Cargo
entityNamePlural: Cargos
description: Cadastro de Cargos
name: cargos
readMenu: Cargos//Visualizar
createMenu: Cargos//Cadastrar
fields: 
  - descricao
  - diaria
  - ferias_impostos
