type: "crud-v1"
entityName: Agendamento Pet Shop
entityNamePlural: Agendamento Pet Shop
description: Agendamento Pet Shop
name: agendamento_pet_shop
readMenu: Visualizar//Agendamentos
createMenu: Cadastrar//Agendamentos
fields: 
  - pet
  - data_da_consulta
  - medico
  - prestador
  - servico
