type: "crud-v1"
entityName: Material
entityNamePlural: Materiais
description: Cadastro de Materiais
name: materiais
readMenu: Visualizar//Materiais
createMenu: Cadastrar//Materiais
fields: 
  - nome
  - preco_de_compra
  - preco_de_venda
