type: "crud-v1"
entityName: Cargo
entityNamePlural: Cargos
description: Cadastro de Cargos
name: cargos
readMenu: Visualizar//Cargos
createMenu: Cadastrar//Cargos
fields: 
  - descricaooooo
  - diaria
  - ferias_impostos
