type: "crud-v1"
entityName: Escopo
entityNamePlural: Escopos
description: Escopo
name: escopo
readMenu: Escopos//Visualizar
createMenu: Escopos//Cadastrar
fields: 
  - agendamento
  - descricao_servico
  - mao_obra
  - materia
