type: "crud-v1"
entityName: Orçamento
entityNamePlural: Orçamentos
description: Orçamentos
name: orcamentos
readMenu: Visualizar//Orçamentos
createMenu: Gerar//Orçamentos
fields: 
  - escopo
  - lucro
  - impostos
  - preco_final
  - mao_obra
  - material
